name: Instazuno
options:
  deploymentTarget:
    iOS: '15.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    CODE_SIGNING_ALLOWED: NO
    MARKETING_VERSION: '1.0.0'
    CURRENT_PROJECT_VERSION: '1'
targets:
  Instazuno:
    type: application
    platform: iOS
    sources:
      - App.swift
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.instazuno.mobile
        TARGETED_DEVICE_FAMILY: '1,2'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Instazuno
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UIUserInterfaceStyle: Light
        NSPhotoLibraryAddUsageDescription: Save the photos and videos you choose to your photo library.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        'UISupportedInterfaceOrientations~ipad':
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    scheme: {}
